import { Dimensions, StyleSheet, Platform, StatusBar } from 'react-native';
import { theme } from "../../theme";
import { textStyles } from '../../textStyles';

const { width: WIDTH, height: HEIGHT } = Dimensions.get('window');
const SCREEN_WIDTH = Dimensions.get('window').width;
const CARD_WIDTH = SCREEN_WIDTH * 0.84;
const SPACING = -18;

export const styles = StyleSheet.create({
    memoContainer: {
        width: CARD_WIDTH,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        // padding: 24,
        borderRadius: 20,
        backgroundColor: '#F8F8F8',
        zIndex: 0,
        // position: 'relative',
    },
    memoText: {
        color: theme.gray30,
        fontFamily: 'PretendardRegular',
        fontSize: 15,
        fontWeight: '400',
        lineHeight: 23,
        letterSpacing: -0.3,
        alignSelf: 'stretch',
        margin: 24,
        //marginTop: -12,
        zIndex: 0,
    },
    readMoreText: {
        color: theme.skyblue,
        textAlign: 'center',
        fontFamily: 'PretendardRegular',
        fontSize: 15,
        fontWeight: '400',
        letterSpacing: -0.3,
        zIndex: 0,
    },
    touchableArea: {
        //padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'pink',
        // left: CARD_WIDTH / 2.5,
        position: 'absolute',
        right: 4,
        top: 6,
    },
    moreIcon: {
        //padding: 10,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
        position: 'absolute',
        right: 4,
        top: 6,
    },
    dropdownMenu: {
        zIndex: 1,
        width: 'auto',
        position: 'absolute',
        paddingVertical: 16,
        top: 8,
        right: 8,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.gray95,
        backgroundColor: 'white',
    },
    dropdownMenuDetail: {
        height: 48,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        alignSelf: 'stretch',
    },
    menuItem: {
        color: theme.gray10,
        fontFamily: 'PretendardRegular',
        fontSize: 16,
        fontWeight: '400',
        letterSpacing: -0.32,
    },
    hideContainer: {
        flexDirection: 'row',
        gap: 6,
        marginTop: 12,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    hideText: {
        color: theme.gray60,
        fontFamily: 'PretendardRegular',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: -0.14
    },
    //modal style
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
        alignItems: 'center'
    },
    modalView: {
        width: '100%',
        height: HEIGHT * 0.8,
        backgroundColor: 'white',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        paddingBottom: 24,
        paddingHorizontal: 16,
        alignItems: 'center',
        position: 'absolute',
        top: '20%'
    },
    modalTitle: {
        flexDirection: 'row',
        paddingVertical: 16,
        paddingHorizontal: 8,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        color: theme.gray10,
        fontFamily: 'PretendardRegular',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 19,
        letterSpacing: -0.32,
        //backgroundColor: 'pink',
        //width: 200,
        zIndex: -10
    },
    modalContent: {
        padding: 24,
        alignItems: 'flex-start',
        gap: 8,
        width: '100%',
        height: 240,
        justifyContent: 'space-between',
        borderRadius: 16,
        backgroundColor: theme.gray95,
    },
    memoInput: {
        color: theme.gray10,
        fontFamily: 'Pretendard',
        fontSize: 16,
        fontWeight: '400',
        lineHeight: 24,
        letterSpacing: -0.32
    },
    lengContainer: {
        width: '100%',
        alignItems: 'flex-end',
        marginTop: 6,
        marginRight: 4,
    },
    memoLeng: {
        color: theme.gray60,
        ...textStyles.body14,
    },
    button: {
        width: '100%',
        height: 48,
        borderRadius: 8,
        paddingVertical: 14,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.gray10,
        position: 'absolute',
        bottom: 16,
        left: 16,
    },
    modalFont: {
        fontFamily: 'PretendardRegular',
        color: theme.gray10,
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 19,
        letterSpacing: -0.32,
        flex: 1,
    },
    memoBtnContainer: {
        flexDirection: 'row',
        width: '100%',
        height: 48,
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
        marginHorizontal: 16,
        marginTop: 32,
    },
    whiteBtn: {
        width: WIDTH * 0.45,
        height: 48,
        paddingVertical: 8,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: theme.gray80,
    },
    blackBtn: {
        width: WIDTH * 0.45,
        height: 48,
        paddingVertical: 8,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        borderWidth: 1,
        backgroundColor: theme.gray10,
        // flex: 1,
    },
    btnFont: {
        fontFamily: 'PretendardRegular',
        color: theme.gray50,
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: -0.32,
    },
    memoContent: {
        alignItems: 'flex-start',
        gap: 8,
        width: '100%',
        height: 'auto',
        justifyContent: 'space-between',
    },
    // 메모 없을 때 
    container: {
        width: CARD_WIDTH,
        paddingVertical: 18,
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 44,
        borderRadius: 20,
        backgroundColor: '#F8F8F8',
    },
    btn: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        alignSelf: 'stretch',
        height: 20
    },
    btnText: {
        color: theme.gray40,
        fontFamily: 'PretendardMedium',
        fontSize: 14,
        fontWeight: '500',
        letterSpacing: -0.14
    },
    writeBtn: {
        width: 20,
        height: 20,
        paddingTop: 4.167,
        paddingRight: 1.429,
        paddingBottom: 2.5,
        paddingLeft: 3.333,
        justifyContent: 'center',
        alignItems: 'center'
    },
    // 삭제 모달
    deleteModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center'
    },
    deleteModalView: {
        width: 304,
        height: 147,
        paddingVertical: 32,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 24,
        borderRadius: 16,
        backgroundColor: 'white'
    },
    deleteModalTitle: {
        // flexDirection: 'row',
        // paddingVertical: 16,
        // paddingHorizontal: 8,
        // justifyContent: 'center',
        // alignItems: 'center',
        //position: 'relative',
        color: theme.gray10,
        fontFamily: 'PretendardRegular',
        fontSize: 16,
        fontWeight: '500',
        lineHeight: 19,
        letterSpacing: -0.32,
        height: 19,
    }
});